import { useEffect, useRef } from "react";
import * as echarts from "echarts";
import WorldMap from "../../assets/worldmap.json";

const SlideFive = () => {
  const chartRef = useRef();

  useEffect(() => {
    if (chartRef.current) return;
    echarts.registerMap("world", WorldMap);

    chartRef.current = echarts.init(
      document.getElementById("worldmap-chart"),
      "light",
      {},
    );

    chartRef.current.setOption({
      title: {
        text: "World Life Expectancy (2021)",
        subtext: "Data from UN.org",
        sublink: "https://population.un.org/wpp/Download/Standard/Population/",
        left: "right",
      },
      visualMap: {
        left: "right",
        min: 40,
        max: 90,
        inRange: {
          color: [
            "#313695",
            "#4575b4",
            "#74add1",
            "#abd9e9",
            "#e0f3f8",
            "#ffffbf",
            "#fee090",
            "#fdae61",
            "#f46d43",
            "#d73027",
            "#a50026",
          ].reverse(),
        },
        text: ["High", "Low"],
        calculable: true,
      },
      series: [
        {
          name: "Life expectancy by countries",
          type: "map",
          roam: true,
          map: "world",
          emphasis: {
            label: {
              show: true,
            },
          },
          data: [
            { name: "Burundi", value: "61.7" },
            { name: "Comoros", value: "63.4" },
            { name: "Djibouti", value: "62.3" },
            { name: "Eritrea", value: "66.5" },
            { name: "Ethiopia", value: "65.0" },
            { name: "Kenya", value: "61.4" },
            { name: "Madagascar", value: "64.5" },
            { name: "Malawi", value: "62.9" },
            { name: "Mauritius", value: "73.6" },
            { name: "Mayotte", value: "74.2" },
            { name: "Mozambique", value: "59.3" },
            { name: "Réunion", value: "81.6" },
            { name: "Rwanda", value: "66.1" },
            { name: "Seychelles", value: "71.3" },
            { name: "Somalia", value: "55.3" },
            { name: "South Sudan", value: "55.0" },
            { name: "Uganda", value: "62.7" },
            { name: "United Republic of Tanzania", value: "66.2" },
            { name: "Zambia", value: "61.2" },
            { name: "Zimbabwe", value: "59.3" },
            { name: "Angola", value: "61.6" },
            { name: "Cameroon", value: "60.3" },
            { name: "Central African Republic", value: "53.9" },
            { name: "Chad", value: "52.5" },
            { name: "Republic of the Congo", value: "63.5" },
            { name: "Democratic Republic of the Congo", value: "59.2" },
            { name: "Equatorial Guinea", value: "60.6" },
            { name: "Gabon", value: "65.8" },
            { name: "Sao Tome and Principe", value: "67.6" },
            { name: "Algeria", value: "76.4" },
            { name: "Egypt", value: "70.2" },
            { name: "Libya", value: "71.9" },
            { name: "Morocco", value: "74.0" },
            { name: "Sudan", value: "65.3" },
            { name: "Tunisia", value: "73.8" },
            { name: "Western Sahara", value: "70.8" },
            { name: "Botswana", value: "61.1" },
            { name: "Eswatini", value: "57.1" },
            { name: "Lesotho", value: "53.1" },
            { name: "Namibia", value: "59.3" },
            { name: "South Africa", value: "62.3" },
            { name: "Benin", value: "59.8" },
            { name: "Burkina Faso", value: "59.3" },
            { name: "Cabo Verde", value: "74.1" },
            { name: "Ivory Coast", value: "58.6" },
            { name: "Gambia", value: "62.1" },
            { name: "Ghana", value: "63.8" },
            { name: "Guinea", value: "58.9" },
            { name: "Guinea Bissau", value: "59.7" },
            { name: "Liberia", value: "60.7" },
            { name: "Mali", value: "58.9" },
            { name: "Mauritania", value: "64.4" },
            { name: "Niger", value: "61.6" },
            { name: "Nigeria", value: "52.7" },
            { name: "Saint Helena", value: "76.8" },
            { name: "Senegal", value: "67.1" },
            { name: "Sierra Leone", value: "60.1" },
            { name: "Togo", value: "61.6" },
            { name: "Kazakhstan", value: "69.4" },
            { name: "Kyrgyzstan", value: "70.0" },
            { name: "Tajikistan", value: "71.6" },
            { name: "Turkmenistan", value: "69.3" },
            { name: "Uzbekistan", value: "70.9" },
            { name: "China", value: "78.2" },
            { name: "China, Hong Kong SAR", value: "85.5" },
            { name: "China, Macao SAR", value: "85.4" },
            { name: "China, Taiwan Province of China", value: "81.0" },
            { name: "North Korea", value: "73.3" },
            { name: "Japan", value: "84.8" },
            { name: "Mongolia", value: "71.0" },
            { name: "South Korea", value: "83.7" },
            { name: "Afghanistan", value: "62.0" },
            { name: "Bangladesh", value: "72.4" },
            { name: "Bhutan", value: "71.8" },
            { name: "India", value: "67.2" },
            { name: "Iran", value: "73.9" },
            { name: "Maldives", value: "79.9" },
            { name: "Nepal", value: "68.5" },
            { name: "Pakistan", value: "66.1" },
            { name: "Sri Lanka", value: "76.4" },
            { name: "Brunei Darussalam", value: "74.6" },
            { name: "Cambodia", value: "69.6" },
            { name: "Indonesia", value: "67.6" },
            { name: "Laos", value: "68.1" },
            { name: "Malaysia", value: "74.9" },
            { name: "Myanmar", value: "65.7" },
            { name: "Philippines", value: "69.3" },
            { name: "Singapore", value: "82.8" },
            { name: "Thailand", value: "78.7" },
            { name: "Timor-Leste", value: "67.7" },
            { name: "Vietnam", value: "73.6" },
            { name: "Armenia", value: "72.0" },
            { name: "Azerbaijan", value: "69.4" },
            { name: "Bahrain", value: "78.8" },
            { name: "Cyprus", value: "81.2" },
            { name: "Georgia", value: "71.7" },
            { name: "Iraq", value: "70.4" },
            { name: "Israel", value: "82.3" },
            { name: "Jordan", value: "74.3" },
            { name: "Kuwait", value: "78.7" },
            { name: "Lebanon", value: "75.0" },
            { name: "Oman", value: "72.5" },
            { name: "Qatar", value: "79.3" },
            { name: "Saudi Arabia", value: "76.9" },
            { name: "State of Palestine", value: "73.5" },
            { name: "Syria", value: "72.1" },
            { name: "Türkiye", value: "76.0" },
            { name: "United Arab Emirates", value: "78.7" },
            { name: "Yemen", value: "63.8" },
            { name: "Belarus", value: "72.4" },
            { name: "Bulgaria", value: "71.8" },
            { name: "Czech Republic", value: "77.7" },
            { name: "Hungary", value: "74.5" },
            { name: "Poland", value: "76.5" },
            { name: "Republic of Moldova", value: "68.8" },
            { name: "Romania", value: "74.2" },
            { name: "Russia", value: "69.4" },
            { name: "Slovakia", value: "74.9" },
            { name: "Ukraine", value: "71.6" },
            { name: "Denmark", value: "81.4" },
            { name: "Estonia", value: "77.1" },
            { name: "Faroe Islands", value: "79.3" },
            { name: "Finland", value: "82.0" },
            { name: "Guernsey", value: "82.2" },
            { name: "Iceland", value: "82.7" },
            { name: "Ireland", value: "82.0" },
            { name: "Isle of Man", value: "80.5" },
            { name: "Jersey", value: "80.7" },
            { name: "Latvia", value: "73.6" },
            { name: "Lithuania", value: "73.7" },
            { name: "Norway", value: "83.2" },
            { name: "Sweden", value: "83.0" },
            { name: "United Kingdom", value: "80.7" },
            { name: "Albania", value: "76.5" },
            { name: "Andorra", value: "80.4" },
            { name: "Bosnia and Herzegovina", value: "75.3" },
            { name: "Croatia", value: "77.6" },
            { name: "Gibraltar", value: "79.3" },
            { name: "Greece", value: "80.1" },
            { name: "Holy See", value: "..." },
            { name: "Italy", value: "82.9" },
            { name: "Kosovo", value: "76.8" },
            { name: "Malta", value: "83.8" },
            { name: "Montenegro", value: "76.3" },
            { name: "Macedonia", value: "73.8" },
            { name: "Portugal", value: "81.0" },
            { name: "San Marino", value: "80.9" },
            { name: "Republic of Serbia", value: "74.2" },
            { name: "Slovenia", value: "80.7" },
            { name: "Spain", value: "83.0" },
            { name: "Austria", value: "81.6" },
            { name: "Belgium", value: "81.9" },
            { name: "France", value: "82.5" },
            { name: "Germany", value: "80.6" },
            { name: "Liechtenstein", value: "83.3" },
            { name: "Luxembourg", value: "82.6" },
            { name: "Monaco", value: "85.9" },
            { name: "Netherlands", value: "81.7" },
            { name: "Switzerland", value: "84.0" },
            { name: "Anguilla", value: "76.6" },
            { name: "Antigua and Barbuda", value: "78.5" },
            { name: "Aruba", value: "74.6" },
            { name: "Bahamas", value: "71.6" },
            { name: "Barbados", value: "77.6" },
            { name: "Bonaire, Sint Eustatius and Saba", value: "75.1" },
            { name: "British Virgin Islands", value: "74.5" },
            { name: "Cayman Islands", value: "75.1" },
            { name: "Cuba", value: "73.7" },
            { name: "Curaçao", value: "75.4" },
            { name: "Dominica", value: "72.8" },
            { name: "Dominican Republic", value: "72.6" },
            { name: "Grenada", value: "74.9" },
            { name: "Guadeloupe", value: "80.5" },
            { name: "Haiti", value: "63.2" },
            { name: "Jamaica", value: "70.5" },
            { name: "Martinique", value: "80.7" },
            { name: "Montserrat", value: "75.6" },
            { name: "Puerto Rico", value: "80.2" },
            { name: "Saint Barthélemy", value: "80.4" },
            { name: "Saint Kitts and Nevis", value: "71.7" },
            { name: "Saint Lucia", value: "71.1" },
            { name: "Saint Martin (French part)", value: "80.4" },
            { name: "Saint Vincent and the Grenadines", value: "69.6" },
            { name: "Sint Maarten (Dutch part)", value: "74.0" },
            { name: "Trinidad and Tobago", value: "73.0" },
            { name: "Turkey", value: "74.6" },
            { name: "United States Virgin Islands", value: "74.7" },
            { name: "Belize", value: "70.5" },
            { name: "Costa Rica", value: "77.0" },
            { name: "El Salvador", value: "70.7" },
            { name: "Guatemala", value: "69.2" },
            { name: "Honduras", value: "70.1" },
            { name: "Mexico", value: "70.2" },
            { name: "Nicaragua", value: "73.8" },
            { name: "Panama", value: "76.2" },
            { name: "Argentina", value: "75.4" },
            { name: "Bolivia", value: "63.6" },
            { name: "Brazil", value: "72.8" },
            { name: "Chile", value: "78.9" },
            { name: "Colombia", value: "72.8" },
            { name: "Ecuador", value: "73.7" },
            { name: "Falkland Islands (Malvinas)", value: "78.6" },
            { name: "French Guiana", value: "74.9" },
            { name: "Guyana", value: "65.7" },
            { name: "Paraguay", value: "70.3" },
            { name: "Peru", value: "72.4" },
            { name: "Suriname", value: "70.3" },
            { name: "Uruguay", value: "75.4" },
            { name: "Venezuela", value: "70.6" },
            { name: "Bermuda", value: "79.3" },
            { name: "Canada", value: "82.7" },
            { name: "Greenland", value: "72.4" },
            { name: "Saint Pierre and Miquelon", value: "77.2" },
            { name: "United States of America", value: "77.2" },
            { name: "Australia", value: "84.5" },
            { name: "New Zealand", value: "82.5" },
            { name: "Fiji", value: "67.1" },
            { name: "New Caledonia", value: "79.0" },
            { name: "Papua New Guinea", value: "65.4" },
            { name: "Solomon Islands", value: "70.3" },
            { name: "Vanuatu", value: "70.4" },
            { name: "Guam", value: "76.7" },
            { name: "Kiribati", value: "67.4" },
            { name: "Marshall Islands", value: "65.3" },
            { name: "Micronesia", value: "70.7" },
            { name: "Nauru", value: "63.6" },
            { name: "Northern Mariana Islands", value: "77.2" },
            { name: "Palau", value: "66.0" },
            { name: "American Samoa", value: "72.5" },
            { name: "Cook Islands", value: "74.8" },
            { name: "French Polynesia", value: "79.5" },
            { name: "Niue", value: "70.8" },
            { name: "Samoa", value: "72.8" },
            { name: "Tokelau", value: "75.2" },
            { name: "Tonga", value: "71.0" },
            { name: "Tuvalu", value: "64.5" },
            { name: "Wallis and Futuna Islands", value: "78.4" },
          ],
        },
      ],
    });
  }, []);

  useEffect(() => {
    const resizeListener = () => chartRef.current.resize();
    window.addEventListener("resize", resizeListener);
    return () => {
      window.removeEventListener("resize", resizeListener);
    };
  }, []);

  return (
    <>
      <h2>How is your country doing?</h2>
      <div id="worldmap-chart" className="chart" />
      <p>
        As you can see in the map above European countries have a better life
        expectancy especially compared to African countries.
      </p>
    </>
  );
};

export default SlideFive;
